[2024-07-02T17:37:05.501+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T17:37:05.508+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bharat_cgpa.sem_5_cgpa manual__2024-07-02T12:06:56.251714+00:00 [queued]>
[2024-07-02T17:37:05.510+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bharat_cgpa.sem_5_cgpa manual__2024-07-02T12:06:56.251714+00:00 [queued]>
[2024-07-02T17:37:05.510+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T17:37:05.517+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sem_5_cgpa> on 2024-07-02 12:06:56.251714+00:00
[2024-07-02T17:37:05.519+0530] {standard_task_runner.py:63} INFO - Started process 60630 to run task
[2024-07-02T17:37:05.521+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bharat_cgpa', 'sem_5_cgpa', 'manual__2024-07-02T12:06:56.251714+00:00', '--job-id', '1399', '--raw', '--subdir', 'DAGS_FOLDER/cgpa1.py', '--cfg-path', '/tmp/tmp7pqt498a']
[2024-07-02T17:37:05.522+0530] {standard_task_runner.py:91} INFO - Job 1399: Subtask sem_5_cgpa
[2024-07-02T17:37:05.537+0530] {task_command.py:426} INFO - Running <TaskInstance: bharat_cgpa.sem_5_cgpa manual__2024-07-02T12:06:56.251714+00:00 [running]> on host ninebit5lm
[2024-07-02T17:37:05.566+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bharat_cgpa' AIRFLOW_CTX_TASK_ID='sem_5_cgpa' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T12:06:56.251714+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T12:06:56.251714+00:00'
[2024-07-02T17:37:05.567+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T17:37:05.567+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T17:37:05.567+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sem1_GPA() missing 1 required positional argument: 'sem1_marks'
[2024-07-02T17:37:05.569+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=bharat_cgpa, task_id=sem_5_cgpa, run_id=manual__2024-07-02T12:06:56.251714+00:00, execution_date=20240702T120656, start_date=20240702T120705, end_date=20240702T120705
[2024-07-02T17:37:05.574+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 1399 for task sem_5_cgpa (sem1_GPA() missing 1 required positional argument: 'sem1_marks'; 60630)
[2024-07-02T17:37:05.612+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T17:37:05.618+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T17:37:05.619+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
