[2024-07-02T14:21:09.925+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T14:21:09.931+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bharat_cgpa.sem_8_cgpa manual__2024-07-02T08:49:54.693751+00:00 [queued]>
[2024-07-02T14:21:09.933+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bharat_cgpa.sem_8_cgpa manual__2024-07-02T08:49:54.693751+00:00 [queued]>
[2024-07-02T14:21:09.933+0530] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-02T14:21:09.940+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sem_8_cgpa> on 2024-07-02 08:49:54.693751+00:00
[2024-07-02T14:21:09.943+0530] {standard_task_runner.py:63} INFO - Started process 25745 to run task
[2024-07-02T14:21:09.944+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bharat_cgpa', 'sem_8_cgpa', 'manual__2024-07-02T08:49:54.693751+00:00', '--job-id', '1314', '--raw', '--subdir', 'DAGS_FOLDER/cgpa1.py', '--cfg-path', '/tmp/tmp4ycndme6']
[2024-07-02T14:21:09.945+0530] {standard_task_runner.py:91} INFO - Job 1314: Subtask sem_8_cgpa
[2024-07-02T14:21:09.959+0530] {task_command.py:426} INFO - Running <TaskInstance: bharat_cgpa.sem_8_cgpa manual__2024-07-02T08:49:54.693751+00:00 [running]> on host ninebit5lm
[2024-07-02T14:21:09.981+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bharat_cgpa' AIRFLOW_CTX_TASK_ID='sem_8_cgpa' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T08:49:54.693751+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T08:49:54.693751+00:00'
[2024-07-02T14:21:09.982+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T14:21:09.982+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T14:21:09.982+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sem1_GPA() missing 1 required positional argument: 'sem1_marks'
[2024-07-02T14:21:09.984+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=bharat_cgpa, task_id=sem_8_cgpa, run_id=manual__2024-07-02T08:49:54.693751+00:00, execution_date=20240702T084954, start_date=20240702T085109, end_date=20240702T085109
[2024-07-02T14:21:09.989+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 1314 for task sem_8_cgpa (sem1_GPA() missing 1 required positional argument: 'sem1_marks'; 25745)
[2024-07-02T14:21:09.996+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T14:21:10.002+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T14:21:10.002+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
